name: Publish Docker Image to Github Packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Github Packages
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ahkeeb6thahkoyao8voh/foobar
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}
